development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://diybeqjpagfwzo:3bda4532341b65639d1e149897c5a80340140bf82e5a0390e1f6bd221466449b@ec2-54-243-46-32.compute-1.amazonaws.com:5432/d6f5copivfcf58
  channel_prefix: QueerBroadsAbroad_production
